### ISSUE TITLE
How to test the model?

### ISSUE THREAD

**Issue by sheryc** [JieyuZ2/TMN#1]
I would like to reproduce the results in the paper, but I cannot find any test scripts in the code, and readme also lacks this part. Any help would be appreciated.

**Comment by JieyuZ2** [comment]
The model will be tested after training: https://github.com/JieyuZ2/TMN/blob/143626237f22060fec5ccfa8451429cf42460a00/base/base_trainer.py#L139

**Comment by sheryc** [comment]
Thanks! :D
