### ISSUE TITLE
Paper abstract corpus

### ISSUE THREAD

**Issue by InesArous** [JieyuZ2/TMN#5]
Hello!
Very impressive work, thank you for sharing your code.
In the paper, you mention that the nodes in the MAG are defined with related paper abstracts corpus. Could you please share the corpus or the textual data related to nodes in the MAG?
Thank you!
Inès

**Comment by JieyuZ2** [comment]
Hey @InesArous 

We used the data released by this [repo](https://github.com/jmshen1994/TaxoExpan), and it seems like they didn't release the original corpus.
