### ISSUE TITLE
Question regarding the train/dev/test split

### ISSUE THREAD

**Issue by lujiaying** [JieyuZ2/TMN#7]
Hi Jieyu, 

thanks for the great work and for making it publically available. 
Just a quick question I could not figure out. In your paper, you mentioned that for `partition_pattern='internal'`, a number of nodes are randomly removed. 

What if the original taxonomy is like:
```
      root
     /    \
   A       B
           /  \
         C     D
                \
                 E
```

Would you consider removing both "B" and "D" for constructing the test set? 
If yes, what would be the ground-truth position for `B`, is it `<root, D>` or `<root, E>`? (worth noting `E` is now in test set, and my speculation is we can not access `E`). 
This is somehow against the independent assumption of expanding $|C|$ independent concepts.

Best,
Jiaying

**Comment by JieyuZ2** [comment]
If I remember correctly: If we remove both B and D, then we will add edges for (root, C) and (root, E). The ground truth for B will be (root, C) and (root, E), while for D it's (root, E).

I'm wondering why we cannot access E? We don't remove it and it's still in the taxonomy?

**Comment by lujiaying** [comment]
Sorry. My bad. That `E` was a typo.
The correct version should be 
> what would be the ground-truth position for B, is it <root, D> or <root, E>? (worth noting `D` is now in test set, and my speculation is we can not access `D`).

**Comment by lujiaying** [comment]
Thank you for the clarification. It helps me better understand your design.
